# github_project:
#   branches: list of primary development branches, else uses repo default
#   close_inactive: close PRs that are inactive for some time (default: false)
#   pr_scanner: trigger the Jenkins PR scanner on PR updates (default: false)
#   redmine: identifier of the Redmine project, optional unless redmine_required=true
#            assigns PRs to tickets, enforces ticket matches project when present
#   redmine_required: enforce commit message format to include Redmine ticket number (default: false)
---
theforeman/chef-handler-foreman:
  redmine: chef
theforeman/community-templates:
  redmine: foreman
theforeman/foreman:
  close_inactive: true
  redmine: foreman
  redmine_required: true
theforeman/foreman_abrt:
  redmine: abrt
theforeman/foreman_ansible:
  pr_scanner: true
  redmine: ansible
  redmine_required: true
theforeman/foreman_azure:
  redmine: azure
  redmine_required: true
theforeman/foreman_bootdisk:
  pr_scanner: true
  redmine: bootdisk
theforeman/foreman_chef:
  redmine: chef
  redmine_required: true
theforeman/foreman_deployments:
  redmine: deployments
theforeman/foreman-digitalocean:
  pr_scanner: true
  redmine: digitalocean
  redmine_required: true
theforeman/foreman_discovery:
  pr_scanner: true
  redmine: discovery
theforeman/foreman-discovery-image:
  redmine: discovery
theforeman/foreman-docker:
  pr_scanner: true
  redmine: docker
  redmine_required: true
theforeman/foreman_expire_hosts:
  pr_scanner: true
theforeman/foreman_host_extra_validator:
  pr_scanner: true
theforeman/foreman_host_rundeck:
  pr_scanner: true
  redmine: rundeck
theforeman/foreman-installer:
  redmine: puppet-foreman
theforeman/foreman-one:
  redmine: opennebula
theforeman/foreman_openscap:
  pr_scanner: true
  redmine: foreman_openscap
  redmine_required: true
theforeman/foreman-packaging:
  branches:
    - deb/develop
    - rpm/develop
  pr_scanner: true
  redmine: rpms
theforeman/foreman_pipeline:
  pr_scanner: true
  redmine: pipeline
theforeman/foreman_remote_execution:
  pr_scanner: true
  redmine: foreman_remote_execution
  redmine_required: true
theforeman/foreman_salt:
  pr_scanner: true
  redmine: salt
theforeman/foreman-selinux:
  redmine: selinux
  redmine_required: true
theforeman/foreman_setup:
  pr_scanner: true
  redmine: foreman_setup
theforeman/foreman_snapshot:
  redmine: snaphost
theforeman/foreman-tasks:
  pr_scanner: true
  redmine: foreman-tasks
  redmine_required: true
theforeman/foreman_templates:
  pr_scanner: true
  redmine: templates
theforeman/foreman-xen:
  redmine: xen
theforeman/hammer-cli:
  pr_scanner: true
  redmine: hammer-cli
theforeman/hammer-cli-foreman:
  pr_scanner: true
  redmine: hammer-cli
theforeman/hammer_cli_foreman_bootdisk:
  redmine: bootdisk
theforeman/hammer-cli-foreman-discovery:
  pr_scanner: true
  redmine: discovery
theforeman/hammer_cli_foreman_docker:
  redmine: docker
theforeman/hammer_cli_foreman_remote_execution:
  redmine: foreman_remote_execution
theforeman/hammer-cli-foreman-tasks:
  redmine: foreman-tasks
theforeman/kafo:
  pr_scanner: true
  redmine: kafo
theforeman/kafo_parsers:
  pr_scanner: true
  redmine: kafo
theforeman/puppet-dhcp:
  redmine: puppet-foreman
theforeman/puppet-dns:
  redmine: puppet-foreman
theforeman/puppet-foreman:
  redmine: puppet-foreman
theforeman/puppet-foreman_proxy:
  redmine: puppet-foreman
theforeman/puppet-git:
  redmine: puppet-foreman
theforeman/puppet-puppet:
  redmine: puppet-foreman
theforeman/puppet-tftp:
  redmine: puppet-foreman
theforeman/smart-proxy:
  redmine: smart-proxy
  redmine_required: true
theforeman/smart_proxy_abrt:
  pr_scanner: true
  redmine: abrt
theforeman/smart_proxy_ansible:
  redmine: ansible
  redmine_required: true
theforeman/smart_proxy_chef:
  redmine: chef
  redmine_required: true
theforeman/smart_proxy_dhcp_infoblox:
  redmine: infoblox
theforeman/smart_proxy_discovery:
  pr_scanner: true
  redmine: discovery
theforeman/smart_proxy_discovery_image:
  redmine: discovery
theforeman/smart_proxy_dns_infoblox:
  redmine: infoblox
theforeman/smart_proxy_dynflow:
  pr_scanner: true
  redmine: foreman_remote_execution
  redmine_required: true
theforeman/smart_proxy_openscap:
  redmine: foreman_openscap
  redmine_required: true
theforeman/smart_proxy_pulp:
  pr_scanner: true
  redmine: katello
theforeman/smart_proxy_remote_execution_ssh:
  pr_scanner: true
  redmine: foreman_remote_execution
  redmine_required: true
theforeman/smart_proxy_salt:
  redmine: salt
theforeman/theforeman.org:
  redmine: foreman-website
Katello/bastion:
  pr_scanner: true
  redmine: bastion
  redmine_required: true
Katello/foreman-gutterball:
  redmine: katello
Katello/foreman_sam:
  redmine: katello
Katello/hammer-cli-csv:
  redmine: hammer-cli-csv
Katello/hammer-cli-gutterball:
  redmine: gutterball
Katello/hammer-cli-import:
  redmine: hammer-cli-import
Katello/hammer-cli-katello:
  redmine: katello
  redmine_required: true
Katello/hammer-cli-sam:
  redmine: katello
Katello/katello:
  pr_scanner: true
  redmine: katello
  redmine_required: true
Katello/katello-agent:
  redmine: katello
Katello/katello-installer:
  redmine: katello
  redmine_required: true
Katello/katello-packaging:
  pr_scanner: true
  redmine: katello-packaging
Katello/katello-selinux:
  redmine: katello
Katello/katello.org:
  redmine: katello
Katello/puppet-capsule:
  redmine: katello
Katello/puppet-certs:
  redmine: katello
Katello/puppet-katello:
  redmine: katello
ohadlevy/stacker:
  redmine: stacker
